config/routes.rb
Rails.application.routes.draw do

  root 'users#index'
  resources :users

post "/users/calculation" =>"users#calculation"

end

app/models/bank_detail.rb
class BankDetail
  include Mongoid::Document
  store_in collection: 'pricing_cms'
  field :bank_name, type: String
  field :processing_type, type: String
  field :processing_amount, type: Integer
  field :rate_type, type: String
  field :rate_sub_type, type: String
  field :base_rate, type: Float
  field :rate, type: Float
  field :rate_comment, type: String
  field :loan_min_vl, type: Integer
  field :loan_max_vl, type: Integer
  field :loan_tenure, type: Integer
  field :property_type, type: Array, default: []
  field :residency_type, type: Array, default: []
  field :empl_type, type: Array, default: []
  field :product, type: Array, default: []
  field :type, type: Array, default: []
  field :loan_label, type: String
  field :textvalue, type: String
  field :status, type: Integer
  field :seq, type: Integer
end

app/models/bank_logo.rb
class BankLogo
  include Mongoid::Document
  store_in collection: 'bank_logo'
  field :bank_name, type: String
  field :logo_base64, type: String
end

app/models/user.rb
class User
  include Mongoid::Document
  field :user_name, type: String
  field :email_id, type: String
  field :mobile_number, type: Integer
  field :loan_amount, type: Integer
  field :tenure, type: Integer
  validates :loan_amount, :presence => true, :numericality => true, length: { minimum: 6, maximum: 10 }
  validates :mobile_number, :presence => true, :numericality => true, length: { minimum: 10, maximum: 10 }
  validates :tenure, :presence => true, :numericality => true, length: { minimum: 1, maximum: 2 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
require 'amortization.rb'
class UsersController < ApplicationController

  def index
    @user_details = User.all
  end

  def new
    @user_detail = User.new
  end
  def show
  	@user_detail = User.find(params[:id])
    loan_amount = @user_detail.loan_amount
    tenure = @user_detail.tenure
    @min_loan = (@user_detail.loan_amount / 2).to_i
    @max_loan = (@user_detail.loan_amount * 4).to_i
    @min_tenure= 1
    @max_tenure = (@user_detail.tenure * 2).to_i
    @display_details = calculation(loan_amount, tenure) 
  end
  


  def create
    @user_detail = User.new(user_detail_params)
    if @user_detail.save
      redirect_to @user_detail
    else
      render 'new'
    end
  end

  def edit
    @user_detail = User.find(params[:id])
  end

  def update
    @user_detail = User.find(params[:id])
   
    if @user_detail.update(user_detail_params)
      redirect_to @user_detail
    else
      render 'edit'
    end
  end

  def destroy
    @user_detail = User.find(params[:id])
    @user_detail.destroy
    redirect_to users_path
  end


  def calculation(loan_amount = params[:loan_amount].to_i, tenure = params[:tenure].to_i)
    display_details = []
    hash = {}
    bank_details = BankDetail.where(:loan_min_vl.lte => loan_amount, :loan_max_vl.gte => loan_amount, :loan_tenure.gte => tenure)
    bank_details.each do |bank_detail|
      bank_logo = BankLogo.where(bank_name: bank_detail.bank_name).first.logo_base64
      emi = Amortization.calculate(loan_amount, bank_detail.rate, tenure)
   

      hash.merge!({"bank_logo" => bank_logo, "interest_rate" => bank_detail.rate, "processing_amount" => bank_detail.processing_amount, "emi" => emi})
      display_details.push(hash.clone)
      hash = {}
    end

    respond_to do |format|
      format.html {
        return display_details
      }
      format.json {
        render json: display_details
      }
    end
  end

  private

  def user_detail_params
  	params.require(:user_detail).permit(:user_name, :email_id, :mobile_number, :loan_amount, :tenure)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RetailLending</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/edit.html.erb
<h1>Edit user details</h1>
<br>

<%= form_for :user_detail, url: user_path(@user_detail), method: :patch  do  |f| %>
 
  <% if @user_detail.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user_detail.errors.count, "error") %> prohibited
        this loan details from being saved:
      </h2>
      <ul>
        <% @user_detail.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :Name %><br>
    <%= f.text_field :user_name %>
  </p>
 
  <p>
    <%= f.label :Email_Id %><br>
    <%= f.text_field :email_id %>
  </p>

  <p>
    <%= f.label :Mobile_Number %><br>
    <%= f.text_field :mobile_number %>
  </p>

<h3>Extra Payments</h3>

  <p>
    <%= f.label :Loan_Amount %><br>
    <%= f.text_field :loan_amount %>
  </p>

  <p>
    <%= f.label :Tenure %><br>
    <%= f.text_field :tenure %>
  </p>

  <p>
    <%= f.submit "Proceed", :class => 'submit-btn'%>
    <%= link_to 'Home', users_path %>
  </p>
  
<% end %>

app/views/users/index.html.erb
<h1>List of previoues inputs</h1>
 <%= link_to 'New Calculation', new_user_path %>
 <br>
 <br>
<table>
  <tr>
    <th style="padding-left: 10px">Name</th>
    <th style="padding-left: 10px">Email</th>
    <th style="padding-left: 10px">Mobile Number</th>
    <th style="padding-left: 10px">Loan amount</th>
    <th style="padding-left: 10px">Tenure</th>
  </tr>
 
  <% @user_details.each do |user_detail| %>
   
    <tr>
      <td style="padding-left: 10px"><%= user_detail.user_name %></td>
      <td style="padding-left: 10px"><%= user_detail.email_id %></td>
      <td style="padding-left: 30px"><%= user_detail.mobile_number %></td>
      <td style="padding-left: 30px"><%= user_detail.loan_amount %></td>
      <td style="padding-left: 10px"><%= user_detail.tenure %></td>
      <td style="padding-left: 30px"><%= link_to 'Show', user_path(user_detail) %></td>
      <td style="padding-left: 10px"><%= link_to 'Edit', edit_user_path(user_detail) %></td>
      <td style="padding-left: 10px"><%= link_to 'Destroy', user_path(user_detail),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/users/new.html.erb
<h1>Enter new user details</h1>
<br>
<%= form_for :user_detail, url: users_path do  |f| %>
 
  <% if @user_detail.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user_detail.errors.count, "error") %> prohibited
        this loan details from being saved:
      </h2>
      <ul>
        <% @user_detail.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :Name %><br>
    <%= f.text_field :user_name %>
  </p>
 
  <p>
    <%= f.label :Email_Id %><br>
    <%= f.text_field :email_id %>
  </p>

  <p>
    <%= f.label :Mobile_Number %><br>
    <%= f.text_field :mobile_number %>
  </p>

<h3>Extra Payments</h3>

  <p>
    <%= f.label :Loan_Amount %><br>
    <%= f.text_field :loan_amount %>
  </p>

  <p>
    <%= f.label :Tenure %><br>
    <%= f.text_field :tenure %>
  </p>

  <p>
    <%= f.submit "Proceed", :class => 'submit-btn'%>
    <%= link_to 'Home', users_path %>
  </p>

  
<% end %>

app/views/users/show.html.erb
<%= link_to 'Home', users_path %>
<%= javascript_tag do %>
window.max_loan = <%= @max_loan %>;
window.min_loan = <%= @min_loan %>;
window.max_tenure = <%= @max_tenure %>;
window.min_tenure = <%= @min_tenure %>;
window.show_loan_amount = <%= @user_detail.loan_amount %>
window.show_tenure = <%= @user_detail.tenure %>
<% end %>

<table width="90%" cellpadding="50" bgcolor="155d84">
  <tr>
    <th colspan="3" style="color:white; font-size:18px; padding-bottom:1px;">Select Loan Amount</th>
    <th colspan="3" style="color:white; font-size:18px; padding-bottom:1px;">Select Tenure</th>
  </tr>
  <tr>
  
  <td width="35%" style="
    padding-bottom: 1px;" bgcolor="#155d84" colspan="3">
    <div id="slider-range-max"></div>
    </td>
    
    <td width="35%" style="
    padding-bottom: 1px;" bgcolor="#155d84" colspan="3">
    <div id="slider-range-max-min"></div>
    </td>
  </tr>
  <tr>
  <td bgcolor="#155d84" width="5%" style="text-align:left; vertical-align:top; padding-top:0; color:white ">
  <%= @min_loan %>
  </td>
    <td style="text-align:center;" bgcolor="#155d84" width="30%" >
      <p>
  <input type="text" id="amount" readonly style="border:0; color:#155d84; font-weight:bold;  font-size:20px; padding:20px; padding-left:150px;">
</p>
    </td>
    <td bgcolor="#155d84" width="5%" style="text-align:right; vertical-align:top; padding-top:0; color:white "> 
  <%= @max_loan %>
  </td>
  <td bgcolor="#155d84" width="5%" style="text-align:left; vertical-align:top; padding-top:0; color:white ">
  <%= @min_tenure %>
  </td>
    <td style="text-align:center;" bgcolor="#155d84" width="30%"> 
        <p>
  <input type="text" id="amount_" readonly style="border:0; color:#155d84; font-weight:bold;  font-size:20px; padding:20px; padding-left:150px;" >
  </td>
    <td bgcolor="#155d84" width="5%" style="text-align:right; vertical-align:top; padding-top:0; color:white "> 
  <%= @max_tenure %>
  </td>
</p> 
    </td>
  </tr>
</table>

<%= hidden_field_tag :task_id, @display_details%>


<div id="table_for_bank"> 
<table cellpadding="10">
  <tr>
    <th>Bank</th>
    <th>Interest Rate</th>
    <th>Charges</th>
    <th>Emi</th>
  </tr>

  
  <% @display_details.each do |display_detail| %>
   <tr>
      <td>
     <%= image_tag "data:image/jpeg;base64,#{display_detail['bank_logo']}" %>
  </td>
      <td><%= display_detail["interest_rate"].round(2)%></td>
      <td><%= display_detail["processing_amount"] %></td>
      <td><%= display_detail["emi"].round(2) %></td>
    </tr>
    <% end %>
  </table>
  </div>
 
 <script>
  $(function() {
  
    $( "#slider-range-max" ).slider({
      range: "min",
      min: window.min_loan,
      max: window.max_loan,
      value: window.show_loan_amount,
      slide: function( event, ui ) {
        $( "#amount" ).val( ui.value );
      }
    });

    $( "#amount" ).val( $( "#slider-range-max" ).slider( "value" ) );

    $("#slider-range-max").on("slidestop", function(event, ui) {
        var tenure = $("#amount_").val();
        var data = {"loan_amount": ui.value, "tenure":tenure} 
        $.ajax({
          type: 'POST',
          url: 'calculation.json',
          data: data,
          dataType: "json",
          success: function(data) {
              var innerHTMLString = '<table cellpadding="10" style="border-spacing: 10px 0;"><tr><th>Bank</th><th>Interest Rate</th><th>Charges</th><th>Emi</th></tr>'
              for(var i=0;i<data.length;i++){
                 var obj = data[i];
                 innerHTMLString += '<tr>'
                 for(var key in obj){
                   if (key == "bank_logo") {
                      innerHTMLString = innerHTMLString + '<td> <img src="data:image/jpeg;base64,' + obj[key] + '"</td>';
                   }
                   if (key == "interest_rate") {
                      innerHTMLString = innerHTMLString + '<td>' + obj[key] + '</td>';
                   }
                   if (key == "processing_amount") {
                      innerHTMLString = innerHTMLString + '<td>' + obj[key] + '</td>';
                   }
                   if (key == "emi") {
                      innerHTMLString = innerHTMLString + '<td>' +  Math.round(obj[key] * 100) / 100 + '</td></tr>';
                   }
                }
              }
              innerHTMLString += '</table>'
            
              $("#table_for_bank").html(innerHTMLString);
          }

        });
    });
  });
  </script>



<div id="slider-range-max-min"></div>
 
 <script>
  $(function() {
  
    $( "#slider-range-max-min" ).slider({
      range: "min",
      min: window.min_tenure,
      max: window.max_tenure,
      value: window.show_tenure,
      slide: function( event, ui ) {
        $( "#amount_" ).val( ui.value );
      }
    });
    $( "#amount_" ).val( $( "#slider-range-max-min" ).slider( "value" ) );

        $("#slider-range-max-min").on("slidestop", function(event, ui) {
        var loan_amount = $("#amount").val();
        var data = {"tenure": ui.value, "loan_amount": loan_amount} 
        console.log(data);
        $.ajax({
          type: 'POST',
          url: 'calculation.json',
          data: data,
          dataType: "json",
          success: function(data) {
              var innerHTMLString = '<table cellpadding="10" style="border-spacing: 10px 0;"><tr><th>Bank</th><th>Interest Rate</th><th>Charges</th><th>Emi</th></tr>'
              for(var i=0;i<data.length;i++){
                 var obj = data[i];
                 innerHTMLString += '<tr>'
                 for(var key in obj){
                   if (key == "bank_logo") {
                      innerHTMLString = innerHTMLString + '<td> <img src="data:image/jpeg;base64,' + obj[key] + '"</td>';
                   }
                   if (key == "interest_rate") {
                      innerHTMLString = innerHTMLString + '<td>' + obj[key] + '</td>';
                   }
                   if (key == "processing_amount") {
                      innerHTMLString = innerHTMLString + '<td>' + obj[key] + '</td>';
                   }
                   if (key == "emi") {
                      innerHTMLString = innerHTMLString + '<td>' +  Math.round(obj[key] * 100) / 100 + '</td></tr>';
                   }
                }
              }
              innerHTMLString += '</table>'
            
              $("#table_for_bank").html(innerHTMLString);
          }

        });
    });

  });
  </script>